spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}
          client-id: ${AUTH_CLIENT_ID}
          client-secret: ${AUTH_CLIENT_SECRET}
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
auth0:
  audience: https://snippet-searcher

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
  api-docs:
    enabled: true
    path: "/docs"

server:
  port: 8084
